global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'monitor'

rule_files:
  - alert.rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'blackbox-ssl'
    metrics_path: /probe
    params:
      module: [http_2xx_get_ssl]
    static_configs:
      - targets:
        - https://google.com

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prober:9115
  
  - job_name: 'blackbox-nossl'
    metrics_path: /probe
    params:
      module: [http_2xx_get]
    static_configs:
      - targets:
        - http://google.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prober:9115

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']
